const { headers } = require('..');
module.exports = function(name) {
  return [
    ...headers(),
    `import React, { useState, useEffect } from 'react';`,
    ``,
    `import withPath from '_base/withPath';`,
    `import SpinView from '_view/SpinView';`,
    ``,
    `import { fetchFrom } from './fetch';`,
    `export const defaultParams = {};`,
    `export const defaultQuery = {};`,
    ``,
    ``,
    `export default withPath(WITH_PATH, defaultParams, defaultQuery)(({`,
    `  match: { params, query, pathOf },`,
    `  location: { pathname, search },`,
    `  history,`,
    `}) => {`,
    `  const [loading, setLoading] = useState(true);`,
    `  useEffect(() => {`,
    `    fetchFrom(pathname, search).then(() => {`,
    `      setLoading(false);`,
    `    });`,
    `  }, [pathname, search]);`,
    ``,
    `  return (`,
    `    <SpinView spinning={loading}>`,
    `      <div>${name}</div>`,
    `    </SpinView>`,
    `  );`,
    `});`,
    ``,
  ].join('\n');
};
